# Generated by Django 2.1.3 on 2019-03-05 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuwrite',
            name='sw_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sw_title', to='st.Write', verbose_name='题目名称'),
            preserve_default=False,
        ),
    ]
