# Generated by Django 2.1.3 on 2019-03-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_stuwrite_sw_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=255, verbose_name='试卷名称')),
                ('pte', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=11, null=True, verbose_name='第一题')),
                ('po', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=11, null=True, verbose_name='第二题')),
                ('pt', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=11, null=True, verbose_name='第三题')),
                ('ps', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=11, null=True, verbose_name='第四题')),
                ('pf', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=11, null=True, verbose_name='第五题')),
                ('pfi', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=11, null=True, verbose_name='第六题')),
                ('psi', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=11, null=True, verbose_name='第七题')),
                ('psv', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=11, null=True, verbose_name='第八题')),
                ('pe', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=11, null=True, verbose_name='第九题')),
                ('pn', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=11, null=True, verbose_name='第十题')),
            ],
        ),
    ]
