# Generated by Django 2.1.3 on 2019-03-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0003_spaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ppaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=255, verbose_name='试卷名称')),
            ],
        ),
        migrations.CreateModel(
            name='Swpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wtitle', models.CharField(max_length=255, verbose_name='题目')),
                ('is_a', models.CharField(max_length=255, null=True, verbose_name='选项A')),
                ('is_b', models.CharField(max_length=255, null=True, verbose_name='选项B')),
                ('is_c', models.CharField(max_length=255, null=True, verbose_name='选项C')),
                ('is_d', models.CharField(max_length=255, null=True, verbose_name='选项D')),
                ('anw', models.CharField(max_length=11, null=True, verbose_name='答案')),
                ('fs', models.CharField(max_length=11, null=True, verbose_name='该题计分')),
            ],
        ),
        migrations.AddField(
            model_name='ppaper',
            name='pte',
            field=models.ManyToManyField(to='st.Swpaper'),
        ),
    ]
