# Generated by Django 2.1.3 on 2019-03-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0004_auto_20190307_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tposts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=255, verbose_name='文章标题')),
                ('views', models.IntegerField(default=0, verbose_name='阅读人数')),
                ('days', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('content', models.TextField(null=True, verbose_name='文章内容')),
            ],
        ),
    ]
