# Generated by Django 2.1.3 on 2019-03-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0005_tposts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tposts',
        ),
    ]
