# Generated by Django 2.1.3 on 2018-12-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Five',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Four',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('four', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Kec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.DecimalField(decimal_places=2, max_digits=4)),
                ('skecs', models.ManyToManyField(to='schools.Kec')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('de', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.English')),
                ('deta', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Math')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=32)),
                ('tclass', models.ManyToManyField(to='schools.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Xec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Yuwen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuwen', models.DecimalField(decimal_places=2, max_digits=4)),
                ('skec', models.ManyToManyField(to='schools.Kec')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='detall',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Yuwen'),
        ),
        migrations.AddField(
            model_name='student',
            name='fiv',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Five'),
        ),
        migrations.AddField(
            model_name='student',
            name='fou',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Four'),
        ),
        migrations.AddField(
            model_name='student',
            name='sclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Class'),
        ),
        migrations.AddField(
            model_name='student',
            name='xecs',
            field=models.ManyToManyField(to='schools.Xec'),
        ),
        migrations.AddField(
            model_name='four',
            name='skecesss',
            field=models.ManyToManyField(to='schools.Kec'),
        ),
        migrations.AddField(
            model_name='five',
            name='skecessss',
            field=models.ManyToManyField(to='schools.Kec'),
        ),
        migrations.AddField(
            model_name='english',
            name='skecess',
            field=models.ManyToManyField(to='schools.Kec'),
        ),
        migrations.AddField(
            model_name='class',
            name='ckec',
            field=models.ManyToManyField(to='schools.Kec'),
        ),
    ]
