# Generated by Django 2.1.3 on 2018-12-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20181201_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='student_day',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
